### ISSUE TITLE
Case-insensitive JSON parsing?

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/O365-UWP-Microsoft-Graph-Snippets#5]
Following up on a suspected JSON-parsing issue discovered at HackNYC: the JSON fields returned by the Microsoft Graph are lowercased. Is the seemingly case-insensitive JSON-parsing demonstrated [here](https://github.com/OfficeDev/O365-UWP-Microsoft-Graph-Snippets/blob/master/O365-UWP-Unified-API-Snippets/Users/UserSnippets.cs#L432) specific to the `Newtonsoft` parser? 

For quick reference, I've attached a sample response for `GET https://graph.microsoft.com/v1.0/me/messages/<id>` below:

```
HTTP/1.1 200 OK
Content-type: application/json
Content-length: 248

{
  "receivedDateTime": "datetime-value",
  "sentDateTime": "datetime-value",
  "hasAttachments": true,
  "subject": "subject-value",
  "body": {
    "contentType": "",
    "content": "content-value"
  },
  "bodyPreview": "bodyPreview-value"
}
```

**Comment by jamescro** [comment]
This was my mistake. At some point the Graph service switched to camel-cased response objects and properties. The JSON parser is case sensitive, so I needed to update the fields I was looking for, but apparently I missed this one. I've committed a fix. Thanks for flagging this!

**Comment by iambmelt** [comment]
And thank you for following up @jamescro!
